site_name: rest_api
site_description: A django REST API
repo_url: https://github.com/jrlcolbourne@gmail.com/rest-spring-tech-test
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/jrlcolbourne@gmail.com">jrlcolbourne@gmail.com</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
